config/routes.rb
get :edit_users_export_fields, controller: :users_export_fields, action: :edit
patch :users_export_fields, controller: :users_export_fields, action: :update

app/models/users_export_field.rb
class UsersExportField < ActiveRecord::Base
  validates :user_id, presence: true
  validates :fields, presence: true

  serialize :fields, JSON

  belongs_to :user, inverse_of: :users_export_field
end

app/controllers/users_export_fields_controller.rb
class UsersExportFieldsController < ApplicationController
  before_filter :check_plugin_enabled

  def edit
    users_export_field
  end

  def update
    users_export_field

    @users_export_field.fields = params['users_export_field']

    if @users_export_field.save
      flash[:notice] = l(:users_export_fields_saved)
      redirect_to users_path
    else
      render action: :edit
    end
  end

  private

  def users_export_field
    return @users_export_field if defined?(@users_export_field)

    user = User.current

    if user.users_export_field.present?
      @users_export_field = user.users_export_field
    else
      @users_export_field = user.build_users_export_field
      @users_export_field.fields = Setting.plugin_users_export['default_fields']
    end
  end

  def check_plugin_enabled
    if Setting.plugin_users_export.nil? or !Setting.plugin_users_export[:users_export_enabled]
      render_404
    end
  end
end

app/views/settings/_users_export.html.erb
<%= stylesheet_link_tag 'users-export.css', plugin: :users_export %>

<table class='plugin_settings users_export'>
  <tr>
    <td>
      <label for='settings_users_export_enabled'>
        <%= l(:users_export_enabled) %>
      </label>
    </td>
    <td>
      <%= check_box_tag 'settings[users_export_enabled]', 1, @settings['users_export_enabled'] %>
    </td>
  </tr>

  <tr class='header'>
    <td>
      <%= l('settings.redmine_fields.header') %>
    </td>
    <td></td>
  </tr>

  <% redmine_fields = GetUsersExportFields.redmine_fields_default %>
  <% redmine_fields.each do |key, value| %>
    <tr>
      <td>
        <label for='settings_default_fields_<%= key %>'>
          <%= l("settings.redmine_fields.#{key}") %>
        </label>
      </td>
      <td>
        <%= check_box_tag "settings[default_fields][#{key}]", 1, @settings['default_fields'][key] %>
      </td>
    </tr>
  <% end %>

  <tr class='header'>
    <td>
      <%= l('settings.custom_fields.header') %>
    </td>
    <td></td>
  </tr>

  <% user_custom_fields = GetUsersExportFields.user_custom_fields_default %>
  <% user_custom_fields.each do |custom_field_data| %>
    <tr>
      <td>
        <label for='settings_default_fields_<%= custom_field_data[:custom_field_id] %>'>
          <%= custom_field_data[:name] %>
        </label>
      </td>
      <td>
        <%= check_box_tag "settings[default_fields][#{custom_field_data[:custom_field_id]}]", 1, custom_field_data[:value] %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users_export_fields/edit.html.erb
<%= stylesheet_link_tag 'users-export.css', plugin: :users_export %>

<h1>
  Настроить поля для выгрузки в XLSX
</h1>

<%= form_tag(users_export_fields_path, :method => 'patch') do %>
  <table class='plugin_settings users_export'>
    <tr class='header'>
      <td>
        <%= l('settings.redmine_fields.header') %>
      </td>
      <td></td>
    </tr>

    <% fields = GetUsersExportFields.redmine_fields_default %>
    <% fields.each do |key, value| %>
      <tr>
        <td>
          <label for='users_export_field_<%= key %>'>
            <%= l("settings.redmine_fields.#{key}") %>
          </label>
        </td>
        <td>
          <%= check_box_tag "users_export_field[#{key}]", 1, @users_export_field.fields[key.to_s].present? %>
        </td>
      </tr>
    <% end %>

    <tr class='header'>
      <td>
        <%= l('settings.custom_fields.header') %>
      </td>
      <td></td>
    </tr>

    <% user_custom_fields = GetUsersExportFields.user_custom_fields_default %>
    <% user_custom_fields.each do |custom_field_data| %>
      <tr>
        <td>
          <label for='users_export_field_<%= custom_field_data[:custom_field_id] %>'>
            <%= custom_field_data[:name] %>
          </label>
        </td>
        <td>
          <%= check_box_tag "users_export_field[#{custom_field_data[:custom_field_id]}]", 1, @users_export_field.fields[custom_field_data[:custom_field_id]].present? %>
        </td>
      </tr>
    <% end %>
  </table>

  <dev class='users_export_buttoms'>
    <%= submit_tag l(:button_save), class: 'submit' %>
    <%= link_to l(:button_cancel), users_url, class: 'back' %>
  </dev>
<% end %>